version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/info.net
file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: scripts/after_install.sh
      timeout: 300000
      runas: root